import numpy as np
import matplotlib.pyplot as plt
x=np.array([1,2,3])
print(x)
print(len(x))
print(x[0])
print(x[0]+3)
print(x[:2])
print(x.dtype)

print(x)
print('*'*10)
x=np.arange(0,6,0.1)
y1=np.sin(x)
y2=np.cos(x)
plt.plot(x,y1,label='sin')
plt.plot(x,y2,linestyle='--',label='cos')
plt.xlabel('x')
plt.ylabel('y')
plt.title('sin&cos')
plt.legend()
plt.show()
print('*'*10)
x2=np.arange(0,101,1)
y1=np.power(x2,2)
y2=x2*100
plt.plot(x2,y1)
plt.plot(x2,y2)
plt.show()
